route:
  receiver: 'slack'
  routes:
    - receiver: 'slack'
      continue: true
    - receiver: 'telegram'
      continue: true

receivers:
  - name: 'slack'
    continue: true
    slack_configs:
      - send_resolved: true
        text: '{{ .CommonAnnotations.description }}'
        username: '${SLACK_USER}'
        channel: '${SLACK_CHANNEL}'
        api_url: '${SLACK_URL}'
  - name: 'telegram'
    continue: true
    telegram_configs:
      - bot_token: '${TELEGRAM_BOT_TOKEN}'
        chat_id: ${TELEGRAM_CHAT_ID}
        message: '{{ .CommonAnnotations.description }}'
        disable_notifications: ${TELEGRAM_DISABLE_NOTIFICATIONS}
