route:
  continue: true
  routes:
    - receiver: 'slack'
    - receiver: 'telegram'

receivers:
  - name: 'slack'
    slack_configs:
      - send_resolved: true
        text: '{{ .CommonAnnotations.description }}'
        username: '${SLACK_USER}'
        channel: '${SLACK_CHANNEL}'
        api_url: '${SLACK_URL}'
  - name: 'telegram'
    telegram_configs:
      - bot_token: '${TELEGRAM_BOT_TOKEN}'
        chat_id: ${TELEGRAM_CHAT_ID}
        message: '{{ template "telegram.default.message" .}}'
        disable_notifications: ${TELEGRAM_DISABLE_NOTIFICATIONS}
