route:
  receiver: 'slack'
  routes:
    - receiver: 'slack'
      continue: true
    - receiver: 'telegram'
      continue: true

receivers:
  - name: 'slack'
    slack_configs:
      - send_resolved: true
        text: '{{ .CommonAnnotations.description }}'
        username: '${SLACK_USER}'
        channel: '${SLACK_CHANNEL}'
        api_url: '${SLACK_URL}'
  - name: 'telegram'
    telegram_configs:
      - send_resolved: true
        api_url: https://api.telegram.org
        bot_token: '${TELEGRAM_BOT_TOKEN}'
        chat_id: ${TELEGRAM_CHAT_ID}
        message: '{{ template "telegram.default.message" .}}'
        parse_mode: '${TELEGRAM_PARSE_MODE}'
        disable_notifications: ${TELEGRAM_DISABLE_NOTIFICATIONS}
