version: '3.9'

services:
  alertmanager:
    image: ${IMAGE_NAME:-prom/alertmanager}:${IMAGE_TAG:-latest}
    entrypoint: ${CONFIG_PATH}/entrypoint.sh
    command:
      - --config.file=${CONFIG_PATH}/alertmanager.yml
      - --storage.path=${DATA_PATH}
      - --web.external-url=https://${TRAEFIK_SUBDOMAIN}.${PUBLIC_HOSTNAME}
    environment:
      CONFIG_PATH:
      SLACK_URL:
      SLACK_CHANNEL:
      SLACK_USER:
      TELEGRAM_BOT_TOKEN:
      TELEGRAM_CHAT_ID:
      TELEGRAM_DISABLE_NOTIFICATIONS:
    networks:
      metric-net:
      traefik-net:
    volumes:
      - alertmanager-vol:${DATA_PATH}
    configs:
      - source: entrypoint-config
        target: ${CONFIG_PATH}/entrypoint.sh
        mode: 0555
      - source: alertmanager-config
        target: ${CONFIG_PATH}/alertmanager-tmpl.yml
    deploy:
      mode: replicated
      replicas: ${REPLICAS:-1}
      restart_policy:
        delay: ${RESTART_DELAY:-10s}
      update_config:
        delay: ${UPDATE_DELAY:-1m}
      labels:
        traefik.enable: ${TRAEFIK_ENABLE:-true}
        traefik.http.routers.alertmanager.entrypoints: ${TRAEFIK_ENTRYPOINT:-http}
        traefik.http.routers.alertmanager.rule: Host(`${TRAEFIK_SUBDOMAIN}.${PUBLIC_HOSTNAME}`)
        traefik.http.middlewares.alertmanager-auth.basicauth.users: ${TRAEFIK_AUTH}
        traefik.http.routers.alertmanager.middlewares: alertmanager-auth
        traefik.http.services.alertmanager.loadbalancer.server.port: ${PORT:-9093}
      resources:
        limits:
          cpus: '${RESOURCES_LIMITS_CPUS:-0.1}'
          memory: ${RESOURCES_LIMITS_MEMORY:-32M}
        reservations:
          cpus: '${RESOURCES_RESERVATIONS_CPUS:-0.001}'
          memory: ${RESOURCES_RESERVATIONS_MEMORY:-16M}

networks:
  metric-net:
    name: ${METRIC_NET_NAME:-metric-net}
    driver: ${METRIC_NET_DRIVER:-overlay}
    external: true

  traefik-net:
    name: ${TRAEFIK_NET_NAME:-traefik-net}
    driver: ${TRAEFIK_NET_DRIVER:-overlay}
    external: true

configs:
  entrypoint-config:
    name: ${ENTRYPOINT_CONFIG_NAME:-alertmanager-entrypoint}
    file: ./config/entrypoint.sh

  alertmanager-config:
    name: ${ALERTMANAGER_CONFIG_NAME:-alertmanager-config}
    file: ./config/alertmanager-tmpl.yml
